/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.EmployeeInfo;
import model.EmployeeInfoHistory;

/**
 *
 * @author yanyanchen
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    
   EmployeeInfoHistory history;
   
    public ViewJPanel(EmployeeInfoHistory history) {
        initComponents();
        
        this.history = history;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        lblTeamInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblContactInfo = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        lblEmployeeID = new javax.swing.JLabel();
        txtPhotoPath = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSearchByName = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblPic = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearchID = new javax.swing.JTextField();
        btnSearchByID = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        cbEmail = new javax.swing.JCheckBox();
        cbPhoneNumber = new javax.swing.JCheckBox();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        cbbAge = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSearchAge = new javax.swing.JTextField();
        btnSearchByAge = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSearchGender = new javax.swing.JTextField();
        btnSearchByGender = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSearchLevel = new javax.swing.JTextField();
        btnSearchByLevel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSearchTeam = new javax.swing.JTextField();
        btnSearchByTeam = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Employee Information");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender ", "Start Date", "Level", "Team info", "Position title", "Contact Info", "Phone number", "Email address ", "Photo"
            }
        ));
        jScrollPane2.setViewportView(tblEmployee);

        lblTeamInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTeamInfo.setText("Team Information:");

        lblPositionTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPositionTitle.setText("Position Title:");

        lblContactInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblContactInfo.setText("Contact Information:");

        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhoneNumber.setText("Cell Phone Number:");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmail.setText("Email Address:");

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhoto.setText("Photo:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtLevel.setMaximumSize(new java.awt.Dimension(64, 23));

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name:");

        lblEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmployeeID.setText("Employee ID:");

        txtPhotoPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhotoPathActionPerformed(evt);
            }
        });

        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAge.setText("Age:");

        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender:");

        lblStartDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStartDate.setText("Start Date:");

        lblLevel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLevel.setText("Level:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSearchByName.setText("Search");
        btnSearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Search String:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblPic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPic.setMaximumSize(new java.awt.Dimension(400, 400));
        lblPic.setMinimumSize(new java.awt.Dimension(400, 400));

        txtSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Name:");

        jLabel4.setText("ID:");

        txtSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchIDActionPerformed(evt);
            }
        });

        btnSearchByID.setText("Search");
        btnSearchByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByIDActionPerformed(evt);
            }
        });

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        cbEmail.setText("Email");

        cbPhoneNumber.setText("Cell-Phone");

        buttonGroup2.add(rbtnMale);
        rbtnMale.setText("Male");

        buttonGroup2.add(rbtnFemale);
        rbtnFemale.setText("Female");

        cbbAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55" }));

        jLabel5.setText("Age:");

        txtSearchAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchAgeActionPerformed(evt);
            }
        });

        btnSearchByAge.setText("Search");
        btnSearchByAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByAgeActionPerformed(evt);
            }
        });

        jLabel6.setText("Gender:");

        txtSearchGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchGenderActionPerformed(evt);
            }
        });

        btnSearchByGender.setText("Search");
        btnSearchByGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByGenderActionPerformed(evt);
            }
        });

        jLabel7.setText("Level:");

        txtSearchLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchLevelActionPerformed(evt);
            }
        });

        btnSearchByLevel.setText("Search");
        btnSearchByLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByLevelActionPerformed(evt);
            }
        });

        jLabel8.setText("Team Info:");

        txtSearchTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchTeamActionPerformed(evt);
            }
        });

        btnSearchByTeam.setText("Search");
        btnSearchByTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBrowse))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchByName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchByID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchAge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchByAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchGender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchByGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchByLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchByTeam)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnFemale)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnMale))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEmail)
                                .addGap(32, 32, 32)
                                .addComponent(cbPhoneNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhotoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch)
                    .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnSearchByName)
                    .addComponent(jLabel4)
                    .addComponent(txtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByID)
                    .addComponent(jLabel5)
                    .addComponent(txtSearchAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByAge)
                    .addComponent(jLabel6)
                    .addComponent(txtSearchGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByGender)
                    .addComponent(jLabel7)
                    .addComponent(txtSearchLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByLevel)
                    .addComponent(jLabel8)
                    .addComponent(txtSearchTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByTeam))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmployeeID))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(cbbAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender)
                            .addComponent(rbtnFemale)
                            .addComponent(rbtnMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStartDate)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLevel)
                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTeamInfo)
                            .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPositionTitle)
                            .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContactInfo)
                            .addComponent(cbEmail)
                            .addComponent(cbPhoneNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPhotoPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBrowse)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEmployee.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to view.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        EmployeeInfo seletedEmployee = (EmployeeInfo)model.getValueAt(selectedRowIndex, 0);
        
        txtName.setText(String.valueOf(seletedEmployee.getName()));
        txtEmployeeID.setText(String.valueOf(seletedEmployee.getEmployeeId()));
        txtStartDate.setText(String.valueOf(seletedEmployee.getStartDate()));
        txtLevel.setText(String.valueOf(seletedEmployee.getLevel()));
        txtTeamInfo.setText(String.valueOf(seletedEmployee.getTeamInfo()));
        txtPositionTitle.setText(String.valueOf(seletedEmployee.getPositionTitle()));
        txtPhoneNumber.setText(String.valueOf(seletedEmployee.getPhoneNumber()));
        txtEmailAddress.setText(String.valueOf(seletedEmployee.getEmailAddress()));
        txtPhotoPath.setText(String.valueOf(seletedEmployee.getPhotoPath()));
        
        String gender =  model.getValueAt(selectedRowIndex, 3).toString();
        if(gender.equals("Female")){
            rbtnFemale.setSelected(true);
        }else if(gender.equals("Male")){
            rbtnMale.setSelected(true);
        }
        
        String ContactInfo = model.getValueAt(selectedRowIndex, 8).toString();
        switch (ContactInfo){
            case "Email ":
                cbEmail.setSelected(true);
                cbPhoneNumber.setSelected(false);
                break;
            case "PhoneNumber ":
                cbEmail.setSelected(false);
                cbPhoneNumber.setSelected(true);
                break;
            case "":
                cbEmail.setSelected(false);
                cbPhoneNumber.setSelected(false);
            default:
                cbEmail.setSelected(true);
                cbPhoneNumber.setSelected(true);
                break;
        }
        
        //display picture
        ImageIcon ii =new ImageIcon(seletedEmployee.getPhotoPath());
        Image img =ii.getImage().getScaledInstance(400, 400,Image.SCALE_SMOOTH);
        lblPic.setIcon(new ImageIcon(img));
        
        String age = model.getValueAt(selectedRowIndex, 2).toString();
        switch (age){
            case " ":
                cbbAge.setSelectedIndex(0);
                break;
            case "18":
                cbbAge.setSelectedIndex(1);
                break;
            case "19":
                cbbAge.setSelectedIndex(2);
                break;
            case "20":
                cbbAge.setSelectedIndex(3);
                break;
            case "21":
                cbbAge.setSelectedIndex(4);
                break;
            case "22":
                cbbAge.setSelectedIndex(5);
                break;
            case "23":
                cbbAge.setSelectedIndex(6);
                break;
            case "24":
                cbbAge.setSelectedIndex(7);
                break;
            case "25":
                cbbAge.setSelectedIndex(8);
                break;
            case "26":
                cbbAge.setSelectedIndex(9);
                break;
            case "27":
                cbbAge.setSelectedIndex(10);
                break;
            case "28":
                cbbAge.setSelectedIndex(11);
                break;
            case "29":
                cbbAge.setSelectedIndex(12);
                break;
            case "30":
                cbbAge.setSelectedIndex(13);
                break;
            case "31":
                cbbAge.setSelectedIndex(14);
                break;
            case "32":
                cbbAge.setSelectedIndex(15);
                break;
            case "33":
                cbbAge.setSelectedIndex(16);
                break;
            case "34":
                cbbAge.setSelectedIndex(17);
                break;
            case "35":
                cbbAge.setSelectedIndex(18);
                break;
            case "36":
                cbbAge.setSelectedIndex(19);
                break;
            case "37":
                cbbAge.setSelectedIndex(20);
                break;
            case "38":
                cbbAge.setSelectedIndex(21);
                break;
            case "39":
                cbbAge.setSelectedIndex(22);
                break;
            case "40":
                cbbAge.setSelectedIndex(23);
                break;
            case "41":
                cbbAge.setSelectedIndex(24);
                break;
            case "42":
                cbbAge.setSelectedIndex(25);
                break;
            case "43":
                cbbAge.setSelectedIndex(26);
                break;
            case "44":
                cbbAge.setSelectedIndex(27);
                break;
            case "45":
                cbbAge.setSelectedIndex(28);
                break;
            case "46":
                cbbAge.setSelectedIndex(29);
                break;
            case "47":
                cbbAge.setSelectedIndex(30);
                break;
            case "48":
                cbbAge.setSelectedIndex(31);
                break;
            case "49":
                cbbAge.setSelectedIndex(32);
                break;
            case "50":
                cbbAge.setSelectedIndex(33);
                break;
            case "51":
                cbbAge.setSelectedIndex(34);
                break;
            case "52":
                cbbAge.setSelectedIndex(35);
                break;
            case "53":
                cbbAge.setSelectedIndex(36);
                break;
            case "54":
                cbbAge.setSelectedIndex(37);
                break;
            case "55":
                cbbAge.setSelectedIndex(38);
                break;
        }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEmployee.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        EmployeeInfo seletedEmployee = (EmployeeInfo)model.getValueAt(selectedRowIndex, 0);
        
        history.deleteEmployee(seletedEmployee);
        
        
         JOptionPane.showMessageDialog(this,"Employee information deleted.");
         
         populateTable();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhotoPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhotoPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhotoPathActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEmployee.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to update.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        EmployeeInfo seletedEmployee = (EmployeeInfo)model.getValueAt(selectedRowIndex, 0);
        
        String name = txtName.getText();
        String employeeId = txtEmployeeID.getText();
        String age = cbbAge.getSelectedItem().toString();;
        String startDate = txtStartDate.getText();
        String level = txtLevel.getText();
        String teamInfo = txtTeamInfo.getText();
        String positionTitle = txtPositionTitle.getText();
        String phoneNumber = txtPhoneNumber.getText();
        String emailAddress = txtEmailAddress.getText();
        String Photo = txtPhotoPath.getText();
        
        String gender = "";
        if(rbtnFemale.isSelected()){
            gender="Female";
        }
        if(rbtnMale.isSelected()){
            gender="Male";
        }
        
        String contactInfo = "";
        if(cbPhoneNumber.isSelected()){
            contactInfo+=cbPhoneNumber.getText()+" ";
        }
        if(cbEmail.isSelected()){
            contactInfo+=cbEmail.getText()+" ";
        }
        
        EmployeeInfo ei = history.updateEmployee(seletedEmployee);
        
        ei.setAge(age);
        ei.setContactInfo(contactInfo);
        ei.setEmailAddress(emailAddress);
        ei.setEmployeeId(employeeId);
        ei.setGender(gender);
        ei.setLevel(level);
        ei.setName(name);
        ei.setPhoneNumber(phoneNumber);
        ei.setPhotoPath(Photo);
        ei.setPositionTitle(positionTitle);
        ei.setStartDate(startDate);
        ei.setTeamInfo(teamInfo);
        
        
        JOptionPane.showMessageDialog(this,"Employee information updated.");
         
        populateTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByNameActionPerformed
        // TODO add your handling code here:
//        TableModel tableModel = new DefaultTableModel(history.searchEmployeeByName(txtName.getText()),);
//        tblEmployee.setModel(tableModel);
        String name = txtSearchName.getText();
        ArrayList<EmployeeInfo> searched = new ArrayList<EmployeeInfo>();
        searched = history.searchEmployeeByName(name);
        if(searched.size() > 0) {
            //refresh table
            showTable(searched);
        } else {
            //display an error
            JOptionPane.showMessageDialog(this,"No Employee information searched.");
        }
        
        
    }//GEN-LAST:event_btnSearchByNameActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String searchString=txtSearch.getText();
        simpleSearch(searchString);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchNameActionPerformed

    private void txtSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchIDActionPerformed

    private void btnSearchByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByIDActionPerformed
        // TODO add your handling code here:
        String id = txtSearchID.getText();
        ArrayList<EmployeeInfo> searched = new ArrayList<EmployeeInfo>();
        searched = history.searchEmployeeByID(id);
        if(searched.size() > 0) {
            //refresh table
            showTable(searched);
        } else {
            //display an error
            JOptionPane.showMessageDialog(this,"No Employee information searched.");
        }
    }//GEN-LAST:event_btnSearchByIDActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG","png","jpeg","jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);
        if(load == fileChooser.APPROVE_OPTION){
            File f = fileChooser.getSelectedFile();
            String path = f.getAbsolutePath();
            txtPhotoPath.setText(path);
            ImageIcon ii =new ImageIcon(path);
            Image img =ii.getImage().getScaledInstance(400, 400,Image.SCALE_SMOOTH);
            lblPic.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtSearchAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchAgeActionPerformed

    private void btnSearchByAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByAgeActionPerformed
        // TODO add your handling code here:
        String age = txtSearchAge.getText();
        ArrayList<EmployeeInfo> searched = new ArrayList<EmployeeInfo>();
        searched = history.searchEmployeeByAge(age);
        if(searched.size() > 0) {
            //refresh table
            showTable(searched);
        } else {
            //display an error
            JOptionPane.showMessageDialog(this,"No Employee information searched.");
        }
    }//GEN-LAST:event_btnSearchByAgeActionPerformed

    private void txtSearchGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchGenderActionPerformed

    private void btnSearchByGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByGenderActionPerformed
        // TODO add your handling code here:
        String gender = txtSearchGender.getText();
        ArrayList<EmployeeInfo> searched = new ArrayList<EmployeeInfo>();
        searched = history.searchEmployeeByGender(gender);
        if(searched.size() > 0) {
            //refresh table
            showTable(searched);
        } else {
            //display an error
            JOptionPane.showMessageDialog(this,"No Employee information searched.");
        }
        
    }//GEN-LAST:event_btnSearchByGenderActionPerformed

    private void txtSearchLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchLevelActionPerformed

    private void btnSearchByLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByLevelActionPerformed
        // TODO add your handling code here:
        String level = txtSearchLevel.getText();
        ArrayList<EmployeeInfo> searched = new ArrayList<EmployeeInfo>();
        searched = history.searchEmployeeByLevel(level);
        if(searched.size() > 0) {
            //refresh table
            showTable(searched);
        } else {
            //display an error
            JOptionPane.showMessageDialog(this,"No Employee information searched.");
        }
        
    }//GEN-LAST:event_btnSearchByLevelActionPerformed

    private void txtSearchTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTeamActionPerformed

    private void btnSearchByTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByTeamActionPerformed
        // TODO add your handling code here:
        String team = txtSearchTeam.getText();
        ArrayList<EmployeeInfo> searched = new ArrayList<EmployeeInfo>();
        searched = history.searchEmployeeByTeam(team);
        if(searched.size() > 0) {
            //refresh table
            showTable(searched);
        } else {
            //display an error
            JOptionPane.showMessageDialog(this,"No Employee information searched.");
        }
    }//GEN-LAST:event_btnSearchByTeamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchByAge;
    private javax.swing.JButton btnSearchByGender;
    private javax.swing.JButton btnSearchByID;
    private javax.swing.JButton btnSearchByLevel;
    private javax.swing.JButton btnSearchByName;
    private javax.swing.JButton btnSearchByTeam;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JCheckBox cbEmail;
    private javax.swing.JCheckBox cbPhoneNumber;
    private javax.swing.JComboBox<String> cbbAge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContactInfo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhotoPath;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchAge;
    private javax.swing.JTextField txtSearchGender;
    private javax.swing.JTextField txtSearchID;
    private javax.swing.JTextField txtSearchLevel;
    private javax.swing.JTextField txtSearchName;
    private javax.swing.JTextField txtSearchTeam;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        
        for(EmployeeInfo ei :history.getHistory()){
            Object[] row = new Object[12];
            row[0]=ei;
            row[1]=ei.getEmployeeId();
            row[2]=ei.getAge();
            row[3]=ei.getGender();
            row[4]=ei.getStartDate();
            row[5]=ei.getLevel();
            row[6]=ei.getTeamInfo();
            row[7]=ei.getPositionTitle();
            row[8]=ei.getContactInfo();
            row[9]=ei.getPhoneNumber();
            row[10]=ei.getEmailAddress();
            row[11]=ei.getPhotoPath();
            
            
            model.addRow(row);
        }
    }
    
    private void showTable(ArrayList<EmployeeInfo> searched) {
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        
        for(EmployeeInfo ei :searched){
            Object[] row = new Object[12];
            row[0]=ei;
            row[1]=ei.getEmployeeId();
            row[2]=ei.getAge();
            row[3]=ei.getGender();
            row[4]=ei.getStartDate();
            row[5]=ei.getLevel();
            row[6]=ei.getTeamInfo();
            row[7]=ei.getPositionTitle();
            row[8]=ei.getContactInfo();
            row[9]=ei.getPhoneNumber();
            row[10]=ei.getEmailAddress();
            row[11]=ei.getPhotoPath();
            
            model.addRow(row);
        }
    }
    
    public void simpleSearch(String str){
        DefaultTableModel model = (DefaultTableModel)tblEmployee.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        tblEmployee.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
    
    
}
